#!/usr/bin/python
# Quick and dirty "null test". Ask importdaemon to sync some files over from
# my dev box. I have a FTP server there that allows anonymous FTP and has
# a subdir pub/rhoktest1 containing sync{1..4}.mark
# Let's see if the sync code can manage it.

import sys
sys.path.append('..')
from geodb import *




















main()
